### ISSUE TITLE
No longer downloading models

### ISSUE THREAD

**Issue by CadBrad** [qnzhou/ThingiverseCrawler#1]
Thingiverse has been updating their site heavily lately, which may be the reason why, but I can't get the download_model.py script to actually download anything. I have tried Python 2 & 3, and I managed to get to the following error using Python 3.

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 119, in worker
  File "multiprocessing\pool.py", line 44, in mapstar
  File "C:\Users\Bradley\Documents\Extracts\python-3.5.1-embed-win32\ThingiverseCrawler\download_model.py", line 18, in download_single_file
    r = call(command.split());
  File "subprocess.py", line 560, in call
  File "subprocess.py", line 950, in **init**
  File "subprocess.py", line 1220, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./ThingiverseCrawler/download_model.py", line 64, in <module>
    main();
  File "./ThingiverseCrawler/download_model.py", line 60, in main
    pool.map(download_single_file, entries[start:end]);
  File "multiprocessing\pool.py", line 260, in map
  File "multiprocessing\pool.py", line 608, in get
FileNotFoundError: [WinError 2] The system cannot find the file specified

The thingiverse_crawler.py is still working, and the grab_context.py seemed to work on about half of the files in summary.csv. I'm very new to python and am just learning to use it for webscrapping. I'm just not sure how to get past this error and start downloading some .stl files.

**Comment by qnzhou** [comment]
I have just pushed a change to `download_model.py`, can you give it a try?

The old code depends on a linux command `wget` which does not exist on Windows.  I have removed this dependency.  It should be working on any platform now.

**Comment by CadBrad** [comment]
This fixed it for me thanks for the quick reply!

I look forward to breaking it down and understand more about how it works.
